- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml

- name: setup python
  ansible.builtin.import_role:
    name: common
    tasks_from: python.yaml

- name: setup system
  ansible.builtin.import_role:
    name: common
    tasks_from: system-setup.yaml