- name: install mysql
  ansible.builtin.package:
    name: mysql-server
    state: present

- name: enable and start 
  ansible.builtin.service:
    name: mysqld
    enabled: yes
    state: started

- name: install mysql python libraries
  ansible.builtin.pip:
    executable: pip3.9
    name: "{{ item }}"
  loop:
    - botocore
    - boto3

- name: set username and password
  ansible.builtin.command: mysql_secure_installation --set-root-pass {{ MYSQL_ROOT_PASSWORD }}