- name: install mysql
  ansible.builtin.package:
    name: mysql-server
    state: present

- name: enable and start 
  ansible.builtin.service:
    name: mysqld
    enabled: yes
    state: started

- name: set username and password
  ansible.builtin.command: mysql_secure_installation --set-root-pass {{ MYSQL_ROOT_PASSWORD }}